import {
  Monitor,
  Calendar,
  Pen,
  Search,
  File,
  FolderOpen,
  Trash2,
  ClipboardList,
  Plus,
  Play,
  Square,
  Download,
  Clock,
  Wallet,
  Umbrella,
  Copy,
  Bot,
  X,
} from 'lucide-react'

const STROKE = 2.2

export const Icons = {
  monitor: <Monitor size={13} strokeWidth={STROKE} />,
  calendar: <Calendar size={13} strokeWidth={STROKE} />,
  pen: <Pen size={13} strokeWidth={STROKE} />,
  search: <Search size={13} strokeWidth={STROKE} />,
  file: <File size={13} strokeWidth={STROKE} />,
  folder: <FolderOpen size={11} strokeWidth={2} />,
  trash: <Trash2 size={14} strokeWidth={2} />,
  calSmall: <Calendar size={11} strokeWidth={2} style={{ verticalAlign: 'middle', marginRight: 5 }} />,
  clipboard: <ClipboardList size={18} strokeWidth={2} />,
  plus: <Plus size={14} strokeWidth={2.5} />,
  play: <Play size={12} fill="currentColor" strokeWidth={0} />,
  stop: <Square size={12} fill="currentColor" strokeWidth={0} />,
  download: <Download size={13} strokeWidth={STROKE} />,
  clock: <Clock size={40} strokeWidth={1.4} />,
  clockNav: <Clock size={16} strokeWidth={2} />,
  wallet: <Wallet size={16} strokeWidth={2} />,
  leave: <Umbrella size={13} strokeWidth={STROKE} />,
  copy: <Copy size={13} strokeWidth={STROKE} />,
  bot: <Bot size={16} strokeWidth={2} />,
  x: <X size={14} strokeWidth={2} />,
}
